### ISSUE TITLE
Unnecessary Exclamation Point

### ISSUE THREAD

**Issue by jbarrow** [bbaumgar/cs3240-labdemo#1]
I will not be able to use this project until the exclamation point after "hello" (i.e. "hello!") is removed. The extra memory and computational requirements are simply too much.

For replication purposes:
- 2012 MBPr
- OS X Yosemite (10.10.2)
- Python 3.4.2
- Pyenv 20141211

Suggested fix, rewrite Python 3 printing to prevent the printing of "!" characters.

**Comment by brentbaum** [comment]
I'm so sorry :( Fixed in latest commit.
